// Generated by Haxe 3.4.3
#include <hxcpp.h>

#ifndef INCLUDED_tjson_EncodeStyle
#include <tjson/EncodeStyle.h>
#endif

namespace tjson{


static ::String EncodeStyle_obj_sMemberFields[] = {
	HX_HCSTRING("beginObject","\xc8","\x61","\x65","\xaf"),
	HX_HCSTRING("endObject","\xfa","\xcc","\x21","\x55"),
	HX_HCSTRING("beginArray","\xb0","\x7e","\x58","\x9b"),
	HX_HCSTRING("endArray","\xbe","\xff","\x8c","\x23"),
	HX_HCSTRING("firstEntry","\x22","\xc2","\x64","\xae"),
	HX_HCSTRING("entrySeperator","\x0f","\x9b","\xd3","\x44"),
	HX_HCSTRING("keyValueSeperator","\x2f","\x52","\x8b","\x7d"),
	::String(null()) };

static void EncodeStyle_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(EncodeStyle_obj::__mClass,"__mClass");
};

#ifdef HXCPP_VISIT_ALLOCS
static void EncodeStyle_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(EncodeStyle_obj::__mClass,"__mClass");
};

#endif

hx::Class EncodeStyle_obj::__mClass;

void EncodeStyle_obj::__register()
{
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_HCSTRING("tjson.EncodeStyle","\x49","\x24","\x9e","\x63");
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mMarkFunc = EncodeStyle_obj_sMarkStatics;
	__mClass->mMembers = hx::Class_obj::dupFunctions(EncodeStyle_obj_sMemberFields);
	__mClass->mCanCast = hx::TIsInterface< (int)0x6f55723f >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = EncodeStyle_obj_sVisitStatics;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace tjson
