// Generated by Haxe 3.4.3
#include <hxcpp.h>

#ifndef INCLUDED_EReg
#include <EReg.h>
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_Type
#include <Type.h>
#endif
#ifndef INCLUDED_haxe_Utf8
#include <haxe/Utf8.h>
#endif
#ifndef INCLUDED_tjson_TJSON
#include <tjson/TJSON.h>
#endif
#ifndef INCLUDED_tjson_TJSONParser
#include <tjson/TJSONParser.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_8c4c64da12ad2c24_43_new,"tjson.TJSONParser","new",0xd8b03d1b,"tjson.TJSONParser.new","tjson/TJSON.hx",43,0x85b8bad5)
HX_LOCAL_STACK_FRAME(_hx_pos_8c4c64da12ad2c24_56_doParse,"tjson.TJSONParser","doParse",0x197356e3,"tjson.TJSONParser.doParse","tjson/TJSON.hx",56,0x85b8bad5)
HX_LOCAL_STACK_FRAME(_hx_pos_8c4c64da12ad2c24_68_doObject,"tjson.TJSONParser","doObject",0x532f920f,"tjson.TJSONParser.doObject","tjson/TJSON.hx",68,0x85b8bad5)
HX_LOCAL_STACK_FRAME(_hx_pos_8c4c64da12ad2c24_116_doArray,"tjson.TJSONParser","doArray",0x81ad3449,"tjson.TJSONParser.doArray","tjson/TJSON.hx",116,0x85b8bad5)
HX_LOCAL_STACK_FRAME(_hx_pos_8c4c64da12ad2c24_139_convertSymbolToProperType,"tjson.TJSONParser","convertSymbolToProperType",0x8858d24b,"tjson.TJSONParser.convertSymbolToProperType","tjson/TJSON.hx",139,0x85b8bad5)
HX_LOCAL_STACK_FRAME(_hx_pos_8c4c64da12ad2c24_170_looksLikeFloat,"tjson.TJSONParser","looksLikeFloat",0xe4dd3816,"tjson.TJSONParser.looksLikeFloat","tjson/TJSON.hx",170,0x85b8bad5)
HX_LOCAL_STACK_FRAME(_hx_pos_8c4c64da12ad2c24_182_looksLikeInt,"tjson.TJSONParser","looksLikeInt",0x29db0ce9,"tjson.TJSONParser.looksLikeInt","tjson/TJSON.hx",182,0x85b8bad5)
HX_LOCAL_STACK_FRAME(_hx_pos_8c4c64da12ad2c24_185_getNextSymbol,"tjson.TJSONParser","getNextSymbol",0x5b95815c,"tjson.TJSONParser.getNextSymbol","tjson/TJSON.hx",185,0x85b8bad5)
HX_LOCAL_STACK_FRAME(_hx_pos_8c4c64da12ad2c24_348_defaultStringProcessor,"tjson.TJSONParser","defaultStringProcessor",0x357ad6a5,"tjson.TJSONParser.defaultStringProcessor","tjson/TJSON.hx",348,0x85b8bad5)
namespace tjson{

void TJSONParser_obj::__construct(::String vjson,::String __o_vfileName, ::Dynamic stringProcessor){
::String vfileName = __o_vfileName.Default(HX_HCSTRING("JSON Data","\x42","\x37","\x28","\x24"));
            	HX_GC_STACKFRAME(&_hx_pos_8c4c64da12ad2c24_43_new)
HXLINE(  44)		this->json = vjson;
HXLINE(  45)		this->fileName = vfileName;
HXLINE(  46)		this->currentLine = (int)1;
HXLINE(  47)		this->lastSymbolQuoted = false;
HXLINE(  48)		this->pos = (int)0;
HXLINE(  49)		this->floatRegex =  ::EReg_obj::__alloc( HX_CTX ,HX_("^-?[0-9]*\\.[0-9]+$",05,05,e4,a1),HX_("",00,00,00,00));
HXLINE(  50)		this->intRegex =  ::EReg_obj::__alloc( HX_CTX ,HX_("^-?[0-9]+$",65,12,70,cb),HX_("",00,00,00,00));
HXLINE(  51)		 ::Dynamic _hx_tmp;
HXDLIN(  51)		if (hx::IsNull( stringProcessor )) {
HXLINE(  51)			_hx_tmp = this->defaultStringProcessor_dyn();
            		}
            		else {
HXLINE(  51)			_hx_tmp = stringProcessor;
            		}
HXDLIN(  51)		this->strProcessor = _hx_tmp;
HXLINE(  52)		this->cache = ::cpp::VirtualArray_obj::__new();
            	}

Dynamic TJSONParser_obj::__CreateEmpty() { return new TJSONParser_obj; }

void *TJSONParser_obj::_hx_vtable = 0;

Dynamic TJSONParser_obj::__Create(hx::DynamicArray inArgs)
{
	hx::ObjectPtr< TJSONParser_obj > _hx_result = new TJSONParser_obj();
	_hx_result->__construct(inArgs[0],inArgs[1],inArgs[2]);
	return _hx_result;
}

bool TJSONParser_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x7b4dacbf;
}

 ::Dynamic TJSONParser_obj::doParse(){
            	HX_STACKFRAME(&_hx_pos_8c4c64da12ad2c24_56_doParse)
HXDLIN(  56)		try {
            			HX_STACK_CATCHABLE(::String, 0);
HXLINE(  58)			::String _g = this->getNextSymbol();
HXDLIN(  58)			::String _hx_switch_0 = _g;
            			if (  (_hx_switch_0==HX_("[",5b,00,00,00)) ){
HXLINE(  60)				return this->doArray();
HXDLIN(  60)				goto _hx_goto_1;
            			}
            			if (  (_hx_switch_0==HX_("{",7b,00,00,00)) ){
HXLINE(  59)				return this->doObject();
HXDLIN(  59)				goto _hx_goto_1;
            			}
            			/* default */{
HXLINE(  61)				::String s = _g;
HXDLIN(  61)				return this->convertSymbolToProperType(s);
            			}
            			_hx_goto_1:;
            		}
            		catch( ::Dynamic _hx_e){
            			if (_hx_e.IsClass< ::String >() ){
            				HX_STACK_BEGIN_CATCH
            				::String e = _hx_e;
HXLINE(  64)				HX_STACK_DO_THROW(((((this->fileName + HX_(" on line ",0b,0c,b3,49)) + this->currentLine) + HX_(": ",a6,32,00,00)) + e));
            			}
            			else {
            				HX_STACK_DO_THROW(_hx_e);
            			}
            		}
HXLINE(  56)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(TJSONParser_obj,doParse,return )

 ::Dynamic TJSONParser_obj::doObject(){
            	HX_STACKFRAME(&_hx_pos_8c4c64da12ad2c24_68_doObject)
HXLINE(  69)		 ::Dynamic o =  ::Dynamic(hx::Anon_obj::Create(0));
HXLINE(  70)		 ::Dynamic val = HX_("",00,00,00,00);
HXLINE(  71)		::String key;
HXLINE(  72)		bool isClassOb = false;
HXLINE(  73)		this->cache->push(o);
HXLINE(  74)		while((this->pos < this->json.length)){
HXLINE(  75)			key = this->getNextSymbol();
HXLINE(  76)			bool _hx_tmp;
HXDLIN(  76)			if ((key == HX_(",",2c,00,00,00))) {
HXLINE(  76)				_hx_tmp = !(this->lastSymbolQuoted);
            			}
            			else {
HXLINE(  76)				_hx_tmp = false;
            			}
HXDLIN(  76)			if (_hx_tmp) {
HXLINE(  76)				continue;
            			}
HXLINE(  77)			bool _hx_tmp1;
HXDLIN(  77)			if ((key == HX_("}",7d,00,00,00))) {
HXLINE(  77)				_hx_tmp1 = !(this->lastSymbolQuoted);
            			}
            			else {
HXLINE(  77)				_hx_tmp1 = false;
            			}
HXDLIN(  77)			if (_hx_tmp1) {
HXLINE(  79)				bool _hx_tmp2;
HXDLIN(  79)				if (isClassOb) {
HXLINE(  79)					_hx_tmp2 = hx::IsNotNull(  ::Dynamic(o->__Field(HX_("TJ_unserialize",de,34,26,eb),hx::paccDynamic)) );
            				}
            				else {
HXLINE(  79)					_hx_tmp2 = false;
            				}
HXDLIN(  79)				if (_hx_tmp2) {
HXLINE(  80)					o->__Field(HX_("TJ_unserialize",de,34,26,eb),hx::paccDynamic)();
            				}
HXLINE(  82)				return o;
            			}
HXLINE(  85)			::String seperator = this->getNextSymbol();
HXLINE(  86)			if ((seperator != HX_(":",3a,00,00,00))) {
HXLINE(  87)				HX_STACK_DO_THROW(((HX_("Expected ':' but got '",20,3e,36,5d) + seperator) + HX_("' instead.",85,80,01,06)));
            			}
HXLINE(  90)			::String v = this->getNextSymbol();
HXLINE(  92)			if ((key == HX_("_hxcls",db,b3,30,2d))) {
HXLINE(  93)				hx::Class cls = ::Type_obj::resolveClass(v);
HXLINE(  94)				if (hx::IsNull( cls )) {
HXLINE(  94)					HX_STACK_DO_THROW((HX_("Invalid class name - ",17,0b,a3,6f) + v));
            				}
HXLINE(  95)				o = ::Type_obj::createEmptyInstance(cls);
HXLINE(  96)				this->cache->pop();
HXLINE(  97)				this->cache->push(o);
HXLINE(  98)				isClassOb = true;
HXLINE(  99)				continue;
            			}
HXLINE( 103)			bool _hx_tmp3;
HXDLIN( 103)			if ((v == HX_("{",7b,00,00,00))) {
HXLINE( 103)				_hx_tmp3 = !(this->lastSymbolQuoted);
            			}
            			else {
HXLINE( 103)				_hx_tmp3 = false;
            			}
HXDLIN( 103)			if (_hx_tmp3) {
HXLINE( 104)				val = this->doObject();
            			}
            			else {
HXLINE( 105)				bool _hx_tmp4;
HXDLIN( 105)				if ((v == HX_("[",5b,00,00,00))) {
HXLINE( 105)					_hx_tmp4 = !(this->lastSymbolQuoted);
            				}
            				else {
HXLINE( 105)					_hx_tmp4 = false;
            				}
HXDLIN( 105)				if (_hx_tmp4) {
HXLINE( 106)					val = this->doArray();
            				}
            				else {
HXLINE( 108)					val = this->convertSymbolToProperType(v);
            				}
            			}
HXLINE( 110)			::Reflect_obj::setField(o,key,val);
            		}
HXLINE( 112)		HX_STACK_DO_THROW(HX_("Unexpected end of file. Expected '}'",8c,66,05,48));
HXDLIN( 112)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(TJSONParser_obj,doObject,return )

 ::Dynamic TJSONParser_obj::doArray(){
            	HX_STACKFRAME(&_hx_pos_8c4c64da12ad2c24_116_doArray)
HXLINE( 117)		::cpp::VirtualArray a = ::cpp::VirtualArray_obj::__new();
HXLINE( 118)		 ::Dynamic val;
HXLINE( 119)		while((this->pos < this->json.length)){
HXLINE( 120)			val = this->getNextSymbol();
HXLINE( 121)			bool _hx_tmp;
HXDLIN( 121)			if (hx::IsEq( val,HX_(",",2c,00,00,00) )) {
HXLINE( 121)				_hx_tmp = !(this->lastSymbolQuoted);
            			}
            			else {
HXLINE( 121)				_hx_tmp = false;
            			}
HXDLIN( 121)			if (_hx_tmp) {
HXLINE( 122)				continue;
            			}
            			else {
HXLINE( 124)				bool _hx_tmp1;
HXDLIN( 124)				if (hx::IsEq( val,HX_("]",5d,00,00,00) )) {
HXLINE( 124)					_hx_tmp1 = !(this->lastSymbolQuoted);
            				}
            				else {
HXLINE( 124)					_hx_tmp1 = false;
            				}
HXDLIN( 124)				if (_hx_tmp1) {
HXLINE( 125)					return a;
            				}
            				else {
HXLINE( 127)					bool _hx_tmp2;
HXDLIN( 127)					if (hx::IsEq( val,HX_("{",7b,00,00,00) )) {
HXLINE( 127)						_hx_tmp2 = !(this->lastSymbolQuoted);
            					}
            					else {
HXLINE( 127)						_hx_tmp2 = false;
            					}
HXDLIN( 127)					if (_hx_tmp2) {
HXLINE( 128)						val = this->doObject();
            					}
            					else {
HXLINE( 129)						bool _hx_tmp3;
HXDLIN( 129)						if (hx::IsEq( val,HX_("[",5b,00,00,00) )) {
HXLINE( 129)							_hx_tmp3 = !(this->lastSymbolQuoted);
            						}
            						else {
HXLINE( 129)							_hx_tmp3 = false;
            						}
HXDLIN( 129)						if (_hx_tmp3) {
HXLINE( 130)							val = this->doArray();
            						}
            						else {
HXLINE( 132)							val = this->convertSymbolToProperType(( (::String)(val) ));
            						}
            					}
            				}
            			}
HXLINE( 134)			a->push(val);
            		}
HXLINE( 136)		HX_STACK_DO_THROW(HX_("Unexpected end of file. Expected ']'",ac,4a,05,48));
HXDLIN( 136)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(TJSONParser_obj,doArray,return )

 ::Dynamic TJSONParser_obj::convertSymbolToProperType(::String symbol){
            	HX_STACKFRAME(&_hx_pos_8c4c64da12ad2c24_139_convertSymbolToProperType)
HXLINE( 140)		if (this->lastSymbolQuoted) {
HXLINE( 143)			if (::StringTools_obj::startsWith(symbol,::tjson::TJSON_obj::OBJECT_REFERENCE_PREFIX)) {
HXLINE( 144)				int idx = ::Std_obj::parseInt(symbol.substr(::tjson::TJSON_obj::OBJECT_REFERENCE_PREFIX.length,null()));
HXLINE( 145)				return this->cache->__get(idx);
            			}
HXLINE( 147)			return symbol;
            		}
HXLINE( 149)		if (this->looksLikeFloat(symbol)) {
HXLINE( 150)			return ::Std_obj::parseFloat(symbol);
            		}
HXLINE( 152)		if (this->looksLikeInt(symbol)) {
HXLINE( 153)			return ::Std_obj::parseInt(symbol);
            		}
HXLINE( 155)		if ((symbol.toLowerCase() == HX_("true",4e,a7,03,4d))) {
HXLINE( 156)			return true;
            		}
HXLINE( 158)		if ((symbol.toLowerCase() == HX_("false",a3,35,4f,fb))) {
HXLINE( 159)			return false;
            		}
HXLINE( 161)		if ((symbol.toLowerCase() == HX_("null",87,9e,0e,49))) {
HXLINE( 162)			return null();
            		}
HXLINE( 165)		return symbol;
            	}


HX_DEFINE_DYNAMIC_FUNC1(TJSONParser_obj,convertSymbolToProperType,return )

bool TJSONParser_obj::looksLikeFloat(::String s){
            	HX_STACKFRAME(&_hx_pos_8c4c64da12ad2c24_170_looksLikeFloat)
HXDLIN( 170)		if (!(this->floatRegex->match(s))) {
HXDLIN( 170)			if (this->intRegex->match(s)) {
HXLINE( 172)				::String intStr = this->intRegex->matched((int)0);
HXLINE( 173)				if (hx::IsEq( intStr.charCodeAt((int)0),(int)45 )) {
HXLINE( 174)					return (intStr > HX_("-2147483648",5a,57,13,4e));
            				}
            				else {
HXLINE( 176)					return (intStr > HX_("2147483647",ec,7c,fa,a6));
            				}
            			}
            			else {
HXDLIN( 170)				return false;
            			}
            		}
            		else {
HXDLIN( 170)			return true;
            		}
HXDLIN( 170)		return false;
            	}


HX_DEFINE_DYNAMIC_FUNC1(TJSONParser_obj,looksLikeFloat,return )

bool TJSONParser_obj::looksLikeInt(::String s){
            	HX_STACKFRAME(&_hx_pos_8c4c64da12ad2c24_182_looksLikeInt)
HXDLIN( 182)		return this->intRegex->match(s);
            	}


HX_DEFINE_DYNAMIC_FUNC1(TJSONParser_obj,looksLikeInt,return )

::String TJSONParser_obj::getNextSymbol(){
            	HX_GC_STACKFRAME(&_hx_pos_8c4c64da12ad2c24_185_getNextSymbol)
HXLINE( 186)		this->lastSymbolQuoted = false;
HXLINE( 187)		::String c = HX_("",00,00,00,00);
HXLINE( 188)		bool inQuote = false;
HXLINE( 189)		::String quoteType = HX_("",00,00,00,00);
HXLINE( 190)		::String symbol = HX_("",00,00,00,00);
HXLINE( 191)		bool inEscape = false;
HXLINE( 192)		bool inSymbol = false;
HXLINE( 193)		bool inLineComment = false;
HXLINE( 194)		bool inBlockComment = false;
HXLINE( 196)		while((this->pos < this->json.length)){
HXLINE( 197)			::String c1 = this->json;
HXDLIN( 197)			c = c1.charAt(this->pos++);
HXLINE( 198)			bool _hx_tmp;
HXDLIN( 198)			if ((c == HX_("\n",0a,00,00,00))) {
HXLINE( 198)				_hx_tmp = !(inSymbol);
            			}
            			else {
HXLINE( 198)				_hx_tmp = false;
            			}
HXDLIN( 198)			if (_hx_tmp) {
HXLINE( 199)				this->currentLine++;
            			}
HXLINE( 200)			if (inLineComment) {
HXLINE( 201)				bool _hx_tmp1;
HXDLIN( 201)				if ((c != HX_("\n",0a,00,00,00))) {
HXLINE( 201)					_hx_tmp1 = (c == HX_("\r",0d,00,00,00));
            				}
            				else {
HXLINE( 201)					_hx_tmp1 = true;
            				}
HXDLIN( 201)				if (_hx_tmp1) {
HXLINE( 202)					inLineComment = false;
HXLINE( 203)					this->pos++;
            				}
HXLINE( 205)				continue;
            			}
HXLINE( 208)			if (inBlockComment) {
HXLINE( 209)				bool _hx_tmp2;
HXDLIN( 209)				if ((c == HX_("*",2a,00,00,00))) {
HXLINE( 209)					_hx_tmp2 = (this->json.charAt(this->pos) == HX_("/",2f,00,00,00));
            				}
            				else {
HXLINE( 209)					_hx_tmp2 = false;
            				}
HXDLIN( 209)				if (_hx_tmp2) {
HXLINE( 210)					inBlockComment = false;
HXLINE( 211)					this->pos++;
            				}
HXLINE( 213)				continue;
            			}
HXLINE( 216)			if (inQuote) {
HXLINE( 217)				if (inEscape) {
HXLINE( 218)					inEscape = false;
HXLINE( 219)					bool _hx_tmp3;
HXDLIN( 219)					if ((c != HX_("'",27,00,00,00))) {
HXLINE( 219)						_hx_tmp3 = (c == HX_("\"",22,00,00,00));
            					}
            					else {
HXLINE( 219)						_hx_tmp3 = true;
            					}
HXDLIN( 219)					if (_hx_tmp3) {
HXLINE( 220)						symbol = (symbol + c);
HXLINE( 221)						continue;
            					}
HXLINE( 223)					if ((c == HX_("t",74,00,00,00))) {
HXLINE( 224)						symbol = (symbol + HX_("\t",09,00,00,00));
HXLINE( 225)						continue;
            					}
HXLINE( 227)					if ((c == HX_("n",6e,00,00,00))) {
HXLINE( 228)						symbol = (symbol + HX_("\n",0a,00,00,00));
HXLINE( 229)						continue;
            					}
HXLINE( 231)					if ((c == HX_("\\",5c,00,00,00))) {
HXLINE( 232)						symbol = (symbol + HX_("\\",5c,00,00,00));
HXLINE( 233)						continue;
            					}
HXLINE( 235)					if ((c == HX_("r",72,00,00,00))) {
HXLINE( 236)						symbol = (symbol + HX_("\r",0d,00,00,00));
HXLINE( 237)						continue;
            					}
HXLINE( 239)					if ((c == HX_("/",2f,00,00,00))) {
HXLINE( 240)						symbol = (symbol + HX_("/",2f,00,00,00));
HXLINE( 241)						continue;
            					}
HXLINE( 244)					if ((c == HX_("u",75,00,00,00))) {
HXLINE( 245)						int hexValue = (int)0;
HXLINE( 247)						{
HXLINE( 247)							int _g = (int)0;
HXDLIN( 247)							while((_g < (int)4)){
HXLINE( 247)								_g = (_g + (int)1);
HXDLIN( 247)								int i = (_g - (int)1);
HXLINE( 248)								if ((this->pos >= this->json.length)) {
HXLINE( 249)									HX_STACK_DO_THROW(HX_("Unfinished UTF8 character",af,1d,9a,43));
            								}
HXLINE( 250)								::String nc = this->json;
HXDLIN( 250)								 ::Dynamic nc1 = nc.charCodeAt(this->pos++);
HXLINE( 251)								hexValue = ((int)hexValue << (int)(int)4);
HXLINE( 252)								bool _hx_tmp4;
HXDLIN( 252)								if (hx::IsGreaterEq( nc1,(int)48 )) {
HXLINE( 252)									_hx_tmp4 = hx::IsLessEq( nc1,(int)57 );
            								}
            								else {
HXLINE( 252)									_hx_tmp4 = false;
            								}
HXDLIN( 252)								if (_hx_tmp4) {
HXLINE( 253)									hexValue = (hexValue + (nc1 - (int)48));
            								}
            								else {
HXLINE( 254)									bool _hx_tmp5;
HXDLIN( 254)									if (hx::IsGreaterEq( nc1,(int)65 )) {
HXLINE( 254)										_hx_tmp5 = hx::IsLessEq( nc1,(int)70 );
            									}
            									else {
HXLINE( 254)										_hx_tmp5 = false;
            									}
HXDLIN( 254)									if (_hx_tmp5) {
HXLINE( 255)										hexValue = (hexValue + (((int)10 + nc1) - (int)65));
            									}
            									else {
HXLINE( 256)										bool _hx_tmp6;
HXDLIN( 256)										if (hx::IsGreaterEq( nc1,(int)97 )) {
HXLINE( 256)											_hx_tmp6 = hx::IsLessEq( nc1,(int)102 );
            										}
            										else {
HXLINE( 256)											_hx_tmp6 = false;
            										}
HXDLIN( 256)										if (_hx_tmp6) {
HXLINE( 257)											hexValue = (hexValue + (((int)10 + nc1) - (int)95));
            										}
            										else {
HXLINE( 258)											HX_STACK_DO_THROW(HX_("Not a hex digit",7c,d7,ca,e4));
            										}
            									}
            								}
            							}
            						}
HXLINE( 261)						 ::haxe::Utf8 utf =  ::haxe::Utf8_obj::__alloc( HX_CTX ,null());
HXLINE( 262)						utf->addChar(hexValue);
HXLINE( 263)						symbol = (symbol + utf->toString());
HXLINE( 265)						continue;
            					}
HXLINE( 269)					HX_STACK_DO_THROW(((HX_("Invalid escape sequence '\\",5e,a7,c1,e5) + c) + HX_("'",27,00,00,00)));
            				}
            				else {
HXLINE( 271)					if ((c == HX_("\\",5c,00,00,00))) {
HXLINE( 272)						inEscape = true;
HXLINE( 273)						continue;
            					}
HXLINE( 275)					if ((c == quoteType)) {
HXLINE( 276)						return symbol;
            					}
HXLINE( 278)					symbol = (symbol + c);
HXLINE( 279)					continue;
            				}
            			}
            			else {
HXLINE( 285)				if ((c == HX_("/",2f,00,00,00))) {
HXLINE( 286)					::String c2 = this->json.charAt(this->pos);
HXLINE( 289)					if ((c2 == HX_("/",2f,00,00,00))) {
HXLINE( 290)						inLineComment = true;
HXLINE( 291)						this->pos++;
HXLINE( 292)						continue;
            					}
            					else {
HXLINE( 296)						if ((c2 == HX_("*",2a,00,00,00))) {
HXLINE( 297)							inBlockComment = true;
HXLINE( 298)							this->pos++;
HXLINE( 299)							continue;
            						}
            					}
            				}
            			}
HXLINE( 305)			if (inSymbol) {
HXLINE( 306)				bool _hx_tmp7;
HXDLIN( 306)				bool _hx_tmp8;
HXDLIN( 306)				bool _hx_tmp9;
HXDLIN( 306)				bool _hx_tmp10;
HXDLIN( 306)				bool _hx_tmp11;
HXDLIN( 306)				bool _hx_tmp12;
HXDLIN( 306)				bool _hx_tmp13;
HXDLIN( 306)				if ((c != HX_(" ",20,00,00,00))) {
HXLINE( 306)					_hx_tmp13 = (c == HX_("\n",0a,00,00,00));
            				}
            				else {
HXLINE( 306)					_hx_tmp13 = true;
            				}
HXDLIN( 306)				if (!(_hx_tmp13)) {
HXLINE( 306)					_hx_tmp12 = (c == HX_("\r",0d,00,00,00));
            				}
            				else {
HXLINE( 306)					_hx_tmp12 = true;
            				}
HXDLIN( 306)				if (!(_hx_tmp12)) {
HXLINE( 306)					_hx_tmp11 = (c == HX_("\t",09,00,00,00));
            				}
            				else {
HXLINE( 306)					_hx_tmp11 = true;
            				}
HXDLIN( 306)				if (!(_hx_tmp11)) {
HXLINE( 306)					_hx_tmp10 = (c == HX_(",",2c,00,00,00));
            				}
            				else {
HXLINE( 306)					_hx_tmp10 = true;
            				}
HXDLIN( 306)				if (!(_hx_tmp10)) {
HXLINE( 306)					_hx_tmp9 = (c == HX_(":",3a,00,00,00));
            				}
            				else {
HXLINE( 306)					_hx_tmp9 = true;
            				}
HXDLIN( 306)				if (!(_hx_tmp9)) {
HXLINE( 306)					_hx_tmp8 = (c == HX_("}",7d,00,00,00));
            				}
            				else {
HXLINE( 306)					_hx_tmp8 = true;
            				}
HXDLIN( 306)				if (!(_hx_tmp8)) {
HXLINE( 306)					_hx_tmp7 = (c == HX_("]",5d,00,00,00));
            				}
            				else {
HXLINE( 306)					_hx_tmp7 = true;
            				}
HXDLIN( 306)				if (_hx_tmp7) {
HXLINE( 307)					this->pos--;
HXLINE( 308)					return symbol;
            				}
            				else {
HXLINE( 310)					symbol = (symbol + c);
HXLINE( 311)					continue;
            				}
            			}
            			else {
HXLINE( 316)				bool _hx_tmp14;
HXDLIN( 316)				bool _hx_tmp15;
HXDLIN( 316)				bool _hx_tmp16;
HXDLIN( 316)				if ((c != HX_(" ",20,00,00,00))) {
HXLINE( 316)					_hx_tmp16 = (c == HX_("\t",09,00,00,00));
            				}
            				else {
HXLINE( 316)					_hx_tmp16 = true;
            				}
HXDLIN( 316)				if (!(_hx_tmp16)) {
HXLINE( 316)					_hx_tmp15 = (c == HX_("\n",0a,00,00,00));
            				}
            				else {
HXLINE( 316)					_hx_tmp15 = true;
            				}
HXDLIN( 316)				if (!(_hx_tmp15)) {
HXLINE( 316)					_hx_tmp14 = (c == HX_("\r",0d,00,00,00));
            				}
            				else {
HXLINE( 316)					_hx_tmp14 = true;
            				}
HXDLIN( 316)				if (_hx_tmp14) {
HXLINE( 317)					continue;
            				}
HXLINE( 320)				bool _hx_tmp17;
HXDLIN( 320)				bool _hx_tmp18;
HXDLIN( 320)				bool _hx_tmp19;
HXDLIN( 320)				bool _hx_tmp20;
HXDLIN( 320)				bool _hx_tmp21;
HXDLIN( 320)				if ((c != HX_("{",7b,00,00,00))) {
HXLINE( 320)					_hx_tmp21 = (c == HX_("}",7d,00,00,00));
            				}
            				else {
HXLINE( 320)					_hx_tmp21 = true;
            				}
HXDLIN( 320)				if (!(_hx_tmp21)) {
HXLINE( 320)					_hx_tmp20 = (c == HX_("[",5b,00,00,00));
            				}
            				else {
HXLINE( 320)					_hx_tmp20 = true;
            				}
HXDLIN( 320)				if (!(_hx_tmp20)) {
HXLINE( 320)					_hx_tmp19 = (c == HX_("]",5d,00,00,00));
            				}
            				else {
HXLINE( 320)					_hx_tmp19 = true;
            				}
HXDLIN( 320)				if (!(_hx_tmp19)) {
HXLINE( 320)					_hx_tmp18 = (c == HX_(",",2c,00,00,00));
            				}
            				else {
HXLINE( 320)					_hx_tmp18 = true;
            				}
HXDLIN( 320)				if (!(_hx_tmp18)) {
HXLINE( 320)					_hx_tmp17 = (c == HX_(":",3a,00,00,00));
            				}
            				else {
HXLINE( 320)					_hx_tmp17 = true;
            				}
HXDLIN( 320)				if (_hx_tmp17) {
HXLINE( 321)					return c;
            				}
HXLINE( 326)				bool _hx_tmp22;
HXDLIN( 326)				if ((c != HX_("'",27,00,00,00))) {
HXLINE( 326)					_hx_tmp22 = (c == HX_("\"",22,00,00,00));
            				}
            				else {
HXLINE( 326)					_hx_tmp22 = true;
            				}
HXDLIN( 326)				if (_hx_tmp22) {
HXLINE( 327)					inQuote = true;
HXLINE( 328)					quoteType = c;
HXLINE( 329)					this->lastSymbolQuoted = true;
HXLINE( 330)					continue;
            				}
            				else {
HXLINE( 332)					inSymbol = true;
HXLINE( 333)					symbol = c;
HXLINE( 334)					continue;
            				}
            			}
            		}
HXLINE( 340)		if (inQuote) {
HXLINE( 341)			HX_STACK_DO_THROW(((HX_("Unexpected end of data. Expected ( ",4f,f1,a0,3b) + quoteType) + HX_(" )",09,1c,00,00)));
            		}
HXLINE( 343)		return symbol;
            	}


HX_DEFINE_DYNAMIC_FUNC0(TJSONParser_obj,getNextSymbol,return )

 ::Dynamic TJSONParser_obj::defaultStringProcessor(::String str){
            	HX_STACKFRAME(&_hx_pos_8c4c64da12ad2c24_348_defaultStringProcessor)
HXDLIN( 348)		return str;
            	}


HX_DEFINE_DYNAMIC_FUNC1(TJSONParser_obj,defaultStringProcessor,return )


hx::ObjectPtr< TJSONParser_obj > TJSONParser_obj::__new(::String vjson,::String __o_vfileName, ::Dynamic stringProcessor) {
	hx::ObjectPtr< TJSONParser_obj > __this = new TJSONParser_obj();
	__this->__construct(vjson,__o_vfileName,stringProcessor);
	return __this;
}

hx::ObjectPtr< TJSONParser_obj > TJSONParser_obj::__alloc(hx::Ctx *_hx_ctx,::String vjson,::String __o_vfileName, ::Dynamic stringProcessor) {
	TJSONParser_obj *__this = (TJSONParser_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(TJSONParser_obj), true, "tjson.TJSONParser"));
	*(void **)__this = TJSONParser_obj::_hx_vtable;
	__this->__construct(vjson,__o_vfileName,stringProcessor);
	return __this;
}

TJSONParser_obj::TJSONParser_obj()
{
}

void TJSONParser_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(TJSONParser);
	HX_MARK_MEMBER_NAME(pos,"pos");
	HX_MARK_MEMBER_NAME(json,"json");
	HX_MARK_MEMBER_NAME(lastSymbolQuoted,"lastSymbolQuoted");
	HX_MARK_MEMBER_NAME(fileName,"fileName");
	HX_MARK_MEMBER_NAME(currentLine,"currentLine");
	HX_MARK_MEMBER_NAME(cache,"cache");
	HX_MARK_MEMBER_NAME(floatRegex,"floatRegex");
	HX_MARK_MEMBER_NAME(intRegex,"intRegex");
	HX_MARK_MEMBER_NAME(strProcessor,"strProcessor");
	HX_MARK_END_CLASS();
}

void TJSONParser_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(pos,"pos");
	HX_VISIT_MEMBER_NAME(json,"json");
	HX_VISIT_MEMBER_NAME(lastSymbolQuoted,"lastSymbolQuoted");
	HX_VISIT_MEMBER_NAME(fileName,"fileName");
	HX_VISIT_MEMBER_NAME(currentLine,"currentLine");
	HX_VISIT_MEMBER_NAME(cache,"cache");
	HX_VISIT_MEMBER_NAME(floatRegex,"floatRegex");
	HX_VISIT_MEMBER_NAME(intRegex,"intRegex");
	HX_VISIT_MEMBER_NAME(strProcessor,"strProcessor");
}

hx::Val TJSONParser_obj::__Field(const ::String &inName,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"pos") ) { return hx::Val( pos ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"json") ) { return hx::Val( json ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"cache") ) { return hx::Val( cache ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"doParse") ) { return hx::Val( doParse_dyn() ); }
		if (HX_FIELD_EQ(inName,"doArray") ) { return hx::Val( doArray_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"fileName") ) { return hx::Val( fileName ); }
		if (HX_FIELD_EQ(inName,"intRegex") ) { return hx::Val( intRegex ); }
		if (HX_FIELD_EQ(inName,"doObject") ) { return hx::Val( doObject_dyn() ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"floatRegex") ) { return hx::Val( floatRegex ); }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"currentLine") ) { return hx::Val( currentLine ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"strProcessor") ) { return hx::Val( strProcessor ); }
		if (HX_FIELD_EQ(inName,"looksLikeInt") ) { return hx::Val( looksLikeInt_dyn() ); }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"getNextSymbol") ) { return hx::Val( getNextSymbol_dyn() ); }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"looksLikeFloat") ) { return hx::Val( looksLikeFloat_dyn() ); }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"lastSymbolQuoted") ) { return hx::Val( lastSymbolQuoted ); }
		break;
	case 22:
		if (HX_FIELD_EQ(inName,"defaultStringProcessor") ) { return hx::Val( defaultStringProcessor_dyn() ); }
		break;
	case 25:
		if (HX_FIELD_EQ(inName,"convertSymbolToProperType") ) { return hx::Val( convertSymbolToProperType_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

hx::Val TJSONParser_obj::__SetField(const ::String &inName,const hx::Val &inValue,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"pos") ) { pos=inValue.Cast< int >(); return inValue; }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"json") ) { json=inValue.Cast< ::String >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"cache") ) { cache=inValue.Cast< ::cpp::VirtualArray >(); return inValue; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"fileName") ) { fileName=inValue.Cast< ::String >(); return inValue; }
		if (HX_FIELD_EQ(inName,"intRegex") ) { intRegex=inValue.Cast<  ::EReg >(); return inValue; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"floatRegex") ) { floatRegex=inValue.Cast<  ::EReg >(); return inValue; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"currentLine") ) { currentLine=inValue.Cast< int >(); return inValue; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"strProcessor") ) { strProcessor=inValue.Cast<  ::Dynamic >(); return inValue; }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"lastSymbolQuoted") ) { lastSymbolQuoted=inValue.Cast< bool >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void TJSONParser_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_HCSTRING("pos","\x94","\x5d","\x55","\x00"));
	outFields->push(HX_HCSTRING("json","\x28","\x42","\x68","\x46"));
	outFields->push(HX_HCSTRING("lastSymbolQuoted","\x96","\x66","\x7d","\xc7"));
	outFields->push(HX_HCSTRING("fileName","\xe7","\x5a","\x43","\x62"));
	outFields->push(HX_HCSTRING("currentLine","\xcd","\xf0","\x44","\x80"));
	outFields->push(HX_HCSTRING("cache","\x42","\x9a","\x14","\x41"));
	outFields->push(HX_HCSTRING("floatRegex","\x8b","\x03","\x58","\x05"));
	outFields->push(HX_HCSTRING("intRegex","\x58","\x4f","\x3c","\x2f"));
	super::__GetFields(outFields);
};

#if HXCPP_SCRIPTABLE
static hx::StorageInfo TJSONParser_obj_sMemberStorageInfo[] = {
	{hx::fsInt,(int)offsetof(TJSONParser_obj,pos),HX_HCSTRING("pos","\x94","\x5d","\x55","\x00")},
	{hx::fsString,(int)offsetof(TJSONParser_obj,json),HX_HCSTRING("json","\x28","\x42","\x68","\x46")},
	{hx::fsBool,(int)offsetof(TJSONParser_obj,lastSymbolQuoted),HX_HCSTRING("lastSymbolQuoted","\x96","\x66","\x7d","\xc7")},
	{hx::fsString,(int)offsetof(TJSONParser_obj,fileName),HX_HCSTRING("fileName","\xe7","\x5a","\x43","\x62")},
	{hx::fsInt,(int)offsetof(TJSONParser_obj,currentLine),HX_HCSTRING("currentLine","\xcd","\xf0","\x44","\x80")},
	{hx::fsObject /*cpp::ArrayBase*/ ,(int)offsetof(TJSONParser_obj,cache),HX_HCSTRING("cache","\x42","\x9a","\x14","\x41")},
	{hx::fsObject /*::EReg*/ ,(int)offsetof(TJSONParser_obj,floatRegex),HX_HCSTRING("floatRegex","\x8b","\x03","\x58","\x05")},
	{hx::fsObject /*::EReg*/ ,(int)offsetof(TJSONParser_obj,intRegex),HX_HCSTRING("intRegex","\x58","\x4f","\x3c","\x2f")},
	{hx::fsObject /*Dynamic*/ ,(int)offsetof(TJSONParser_obj,strProcessor),HX_HCSTRING("strProcessor","\x61","\xd6","\xce","\x03")},
	{ hx::fsUnknown, 0, null()}
};
static hx::StaticInfo *TJSONParser_obj_sStaticStorageInfo = 0;
#endif

static ::String TJSONParser_obj_sMemberFields[] = {
	HX_HCSTRING("pos","\x94","\x5d","\x55","\x00"),
	HX_HCSTRING("json","\x28","\x42","\x68","\x46"),
	HX_HCSTRING("lastSymbolQuoted","\x96","\x66","\x7d","\xc7"),
	HX_HCSTRING("fileName","\xe7","\x5a","\x43","\x62"),
	HX_HCSTRING("currentLine","\xcd","\xf0","\x44","\x80"),
	HX_HCSTRING("cache","\x42","\x9a","\x14","\x41"),
	HX_HCSTRING("floatRegex","\x8b","\x03","\x58","\x05"),
	HX_HCSTRING("intRegex","\x58","\x4f","\x3c","\x2f"),
	HX_HCSTRING("strProcessor","\x61","\xd6","\xce","\x03"),
	HX_HCSTRING("doParse","\xa8","\x70","\x82","\xf0"),
	HX_HCSTRING("doObject","\xaa","\x04","\x57","\xa9"),
	HX_HCSTRING("doArray","\x0e","\x4e","\xbc","\x58"),
	HX_HCSTRING("convertSymbolToProperType","\x50","\xc1","\x32","\x79"),
	HX_HCSTRING("looksLikeFloat","\xf1","\x10","\xa5","\x8e"),
	HX_HCSTRING("looksLikeInt","\x04","\x69","\xbf","\x0c"),
	HX_HCSTRING("getNextSymbol","\xe1","\xbc","\x81","\x00"),
	HX_HCSTRING("defaultStringProcessor","\x80","\x82","\x5f","\xa3"),
	::String(null()) };

static void TJSONParser_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(TJSONParser_obj::__mClass,"__mClass");
};

#ifdef HXCPP_VISIT_ALLOCS
static void TJSONParser_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(TJSONParser_obj::__mClass,"__mClass");
};

#endif

hx::Class TJSONParser_obj::__mClass;

void TJSONParser_obj::__register()
{
	hx::Object *dummy = new TJSONParser_obj;
	TJSONParser_obj::_hx_vtable = *(void **)dummy;
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_HCSTRING("tjson.TJSONParser","\xa9","\x13","\xb7","\xa6");
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = TJSONParser_obj_sMarkStatics;
	__mClass->mStatics = hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = hx::Class_obj::dupFunctions(TJSONParser_obj_sMemberFields);
	__mClass->mCanCast = hx::TCanCast< TJSONParser_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = TJSONParser_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = TJSONParser_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = TJSONParser_obj_sStaticStorageInfo;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace tjson
