// Generated by Haxe 3.4.3
#include <hxcpp.h>

#ifndef INCLUDED_haxe_io_Error
#include <haxe/io/Error.h>
#endif
#ifndef INCLUDED_ValueType
#include <ValueType.h>
#endif
#ifndef INCLUDED_Attribute
#include <Attribute.h>
#endif
#ifndef INCLUDED_tjson_TJSON
#include <tjson/TJSON.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_ANSI
#include <ANSI.h>
#endif
#ifndef INCLUDED_tjson_FancyStyle
#include <tjson/FancyStyle.h>
#endif
#ifndef INCLUDED_tjson_SimpleStyle
#include <tjson/SimpleStyle.h>
#endif
#ifndef INCLUDED_tjson_EncodeStyle
#include <tjson/EncodeStyle.h>
#endif
#ifndef INCLUDED_tjson_TJSONEncoder
#include <tjson/TJSONEncoder.h>
#endif
#ifndef INCLUDED_tjson_TJSONParser
#include <tjson/TJSONParser.h>
#endif
#ifndef INCLUDED_sys_io_FileOutput
#include <sys/io/FileOutput.h>
#endif
#ifndef INCLUDED_sys_io_FileInput
#include <sys/io/FileInput.h>
#endif
#ifndef INCLUDED_sys_io_File
#include <sys/io/File.h>
#endif
#ifndef INCLUDED_sys_FileSystem
#include <sys/FileSystem.h>
#endif
#ifndef INCLUDED_orphadb_TablePlayer
#include <orphadb/TablePlayer.h>
#endif
#ifndef INCLUDED_markov_util_StringExtensions
#include <markov/util/StringExtensions.h>
#endif
#ifndef INCLUDED_markov_namegen_Model
#include <markov/namegen/Model.h>
#endif
#ifndef INCLUDED_inside_Util
#include <inside/Util.h>
#endif
#ifndef INCLUDED_inside_Player
#include <inside/Player.h>
#endif
#ifndef INCLUDED_haxe_io_Path
#include <haxe/io/Path.h>
#endif
#ifndef INCLUDED_haxe_io_Eof
#include <haxe/io/Eof.h>
#endif
#ifndef INCLUDED_haxe_io_BytesBuffer
#include <haxe/io/BytesBuffer.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_haxe_ds_EnumValueMap
#include <haxe/ds/EnumValueMap.h>
#endif
#ifndef INCLUDED_haxe_ds_TreeNode
#include <haxe/ds/TreeNode.h>
#endif
#ifndef INCLUDED_haxe_ds_BalancedTree
#include <haxe/ds/BalancedTree.h>
#endif
#ifndef INCLUDED_haxe_Utf8
#include <haxe/Utf8.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_Type
#include <Type.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_Random
#include <Random.h>
#endif
#ifndef INCLUDED__List_ListIterator
#include <_List/ListIterator.h>
#endif
#ifndef INCLUDED__List_ListNode
#include <_List/ListNode.h>
#endif
#ifndef INCLUDED_List
#include <List.h>
#endif
#ifndef INCLUDED_Lambda
#include <Lambda.h>
#endif
#ifndef INCLUDED_Header
#include <Header.h>
#endif
#ifndef INCLUDED__HaxeLowCol_HaxeLowCol_Impl_
#include <_HaxeLowCol/HaxeLowCol_Impl_.h>
#endif
#ifndef INCLUDED_HaxeLow
#include <HaxeLow.h>
#endif
#ifndef INCLUDED_SysDisk
#include <SysDisk.h>
#endif
#ifndef INCLUDED_HaxeLowDisk
#include <HaxeLowDisk.h>
#endif
#ifndef INCLUDED_EReg
#include <EReg.h>
#endif
#ifndef INCLUDED_Date
#include <Date.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_sys_io__Process_Stdout
#include <sys/io/_Process/Stdout.h>
#endif
#ifndef INCLUDED_haxe_io_Input
#include <haxe/io/Input.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_sys_io__Process_Stdin
#include <sys/io/_Process/Stdin.h>
#endif
#ifndef INCLUDED_haxe_io_Output
#include <haxe/io/Output.h>
#endif
#ifndef INCLUDED_sys_io_Process
#include <sys/io/Process.h>
#endif
#ifndef INCLUDED_Sys
#include <Sys.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
hx::RegisterResources( hx::GetResources() );
::haxe::io::Error_obj::__register();
::ValueType_obj::__register();
::Attribute_obj::__register();
::tjson::TJSON_obj::__register();
::StringTools_obj::__register();
::ANSI_obj::__register();
::tjson::FancyStyle_obj::__register();
::tjson::SimpleStyle_obj::__register();
::tjson::EncodeStyle_obj::__register();
::tjson::TJSONEncoder_obj::__register();
::tjson::TJSONParser_obj::__register();
::sys::io::FileOutput_obj::__register();
::sys::io::FileInput_obj::__register();
::sys::io::File_obj::__register();
::sys::FileSystem_obj::__register();
::orphadb::TablePlayer_obj::__register();
::markov::util::StringExtensions_obj::__register();
::markov::namegen::Model_obj::__register();
::inside::Util_obj::__register();
::inside::Player_obj::__register();
::haxe::io::Path_obj::__register();
::haxe::io::Eof_obj::__register();
::haxe::io::BytesBuffer_obj::__register();
::haxe::ds::StringMap_obj::__register();
::haxe::ds::EnumValueMap_obj::__register();
::haxe::ds::TreeNode_obj::__register();
::haxe::ds::BalancedTree_obj::__register();
::haxe::Utf8_obj::__register();
::haxe::IMap_obj::__register();
::Type_obj::__register();
::StringBuf_obj::__register();
::Random_obj::__register();
::_List::ListIterator_obj::__register();
::_List::ListNode_obj::__register();
::List_obj::__register();
::Lambda_obj::__register();
::Header_obj::__register();
::_HaxeLowCol::HaxeLowCol_Impl__obj::__register();
::HaxeLow_obj::__register();
::SysDisk_obj::__register();
::HaxeLowDisk_obj::__register();
::EReg_obj::__register();
::Date_obj::__register();
::Std_obj::__register();
::Reflect_obj::__register();
::sys::io::_Process::Stdout_obj::__register();
::haxe::io::Input_obj::__register();
::haxe::io::Bytes_obj::__register();
::sys::io::_Process::Stdin_obj::__register();
::haxe::io::Output_obj::__register();
::sys::io::Process_obj::__register();
::Sys_obj::__register();
::haxe::io::Error_obj::__boot();
::ValueType_obj::__boot();
::Attribute_obj::__boot();
::ANSI_obj::__boot();
::StringTools_obj::__boot();
::tjson::TJSON_obj::__boot();
}

