// Generated by Haxe 3.4.3
#include <hxcpp.h>

#ifndef INCLUDED_HaxeLowDisk
#include <HaxeLowDisk.h>
#endif



static ::String HaxeLowDisk_obj_sMemberFields[] = {
	HX_HCSTRING("readFileSync","\x6d","\xf0","\xd8","\xa0"),
	HX_HCSTRING("writeFile","\xfb","\xc2","\x6f","\x4c"),
	::String(null()) };

static void HaxeLowDisk_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(HaxeLowDisk_obj::__mClass,"__mClass");
};

#ifdef HXCPP_VISIT_ALLOCS
static void HaxeLowDisk_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(HaxeLowDisk_obj::__mClass,"__mClass");
};

#endif

hx::Class HaxeLowDisk_obj::__mClass;

void HaxeLowDisk_obj::__register()
{
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_HCSTRING("HaxeLowDisk","\x6b","\xbe","\xc3","\xf8");
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mMarkFunc = HaxeLowDisk_obj_sMarkStatics;
	__mClass->mMembers = hx::Class_obj::dupFunctions(HaxeLowDisk_obj_sMemberFields);
	__mClass->mCanCast = hx::TIsInterface< (int)0xf8c3be6b >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = HaxeLowDisk_obj_sVisitStatics;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

