// Generated by Haxe 3.4.3
#ifndef INCLUDED_orphadb_TablePlayer
#define INCLUDED_orphadb_TablePlayer

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_0815dd45fe207986_5_new)
HX_DECLARE_CLASS1(orphadb,TablePlayer)

namespace orphadb{


class HXCPP_CLASS_ATTRIBUTES TablePlayer_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef TablePlayer_obj OBJ_;
		TablePlayer_obj();

	public:
		enum { _hx_ClassId = 0x0b399bef };

		void __construct( ::Dynamic player_params);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="orphadb.TablePlayer")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,true,"orphadb.TablePlayer"); }

		hx::ObjectPtr< TablePlayer_obj > __new( ::Dynamic player_params) {
			hx::ObjectPtr< TablePlayer_obj > __this = new TablePlayer_obj();
			__this->__construct(player_params);
			return __this;
		}

		static hx::ObjectPtr< TablePlayer_obj > __alloc(hx::Ctx *_hx_ctx, ::Dynamic player_params) {
			TablePlayer_obj *__this = (TablePlayer_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(TablePlayer_obj), true, "orphadb.TablePlayer"));
			*(void **)__this = TablePlayer_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_0815dd45fe207986_5_new)
HXLINE(   7)		( ( ::orphadb::TablePlayer)(__this) )->pName = ( (::String)(player_params->__Field(HX_("pName",db,96,b9,b0),hx::paccDynamic)) );
HXDLIN(   7)		( ( ::orphadb::TablePlayer)(__this) )->pAge = ( (int)(player_params->__Field(HX_("pAge",2f,92,39,4a),hx::paccDynamic)) );
HXDLIN(   7)		( ( ::orphadb::TablePlayer)(__this) )->pHp = ( (int)(player_params->__Field(HX_("pHp",98,3b,55,00),hx::paccDynamic)) );
HXDLIN(   7)		( ( ::orphadb::TablePlayer)(__this) )->pMp = ( (int)(player_params->__Field(HX_("pMp",f3,3f,55,00),hx::paccDynamic)) );
HXDLIN(   7)		( ( ::orphadb::TablePlayer)(__this) )->pStr = ( (int)( ::Dynamic(player_params->__Field(HX_("Ability",8a,89,b2,7a),hx::paccDynamic))->__Field(HX_("pStr",21,46,47,4a),hx::paccDynamic)) );
HXLINE(   9)		( ( ::orphadb::TablePlayer)(__this) )->pDex = ( (int)( ::Dynamic(player_params->__Field(HX_("Ability",8a,89,b2,7a),hx::paccDynamic))->__Field(HX_("pDex",47,d7,3b,4a),hx::paccDynamic)) );
HXDLIN(   9)		( ( ::orphadb::TablePlayer)(__this) )->pCon = ( (int)( ::Dynamic(player_params->__Field(HX_("Ability",8a,89,b2,7a),hx::paccDynamic))->__Field(HX_("pCon",b2,1d,3b,4a),hx::paccDynamic)) );
HXDLIN(   9)		( ( ::orphadb::TablePlayer)(__this) )->pInt = ( (int)( ::Dynamic(player_params->__Field(HX_("Ability",8a,89,b2,7a),hx::paccDynamic))->__Field(HX_("pInt",5f,aa,3f,4a),hx::paccDynamic)) );
HXDLIN(   9)		( ( ::orphadb::TablePlayer)(__this) )->pWis = ( (int)( ::Dynamic(player_params->__Field(HX_("Ability",8a,89,b2,7a),hx::paccDynamic))->__Field(HX_("pWis",91,45,4a,4a),hx::paccDynamic)) );
HXDLIN(   9)		( ( ::orphadb::TablePlayer)(__this) )->pCha = ( (int)( ::Dynamic(player_params->__Field(HX_("Ability",8a,89,b2,7a),hx::paccDynamic))->__Field(HX_("pCha",8c,17,3b,4a),hx::paccDynamic)) );
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~TablePlayer_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("TablePlayer","\xef","\x2d","\x2a","\xdb"); }

		::String pName;
		int pAge;
		::String pClass;
		int pHp;
		int pMp;
		int pStr;
		int pDex;
		int pCon;
		int pInt;
		int pWis;
		int pCha;
		 ::Dynamic pCoordinate;
};

} // end namespace orphadb

#endif /* INCLUDED_orphadb_TablePlayer */ 
